version: "2"
services:
  zira-proxy:
    restart: always
    image: zira-proxy
    container_name: zira-proxy
    ports:
      - "80:80"
    networks:
      - front
      - back
networks:
  front:
    driver: bridge
  back:
    driver: bridge
