version: "2"
services:
  zira-proxy:
    restart: always
    image: zira-proxy
    container_name: zira-proxy
    ports:
      - "80:80"
    networks:
      - zira
networks:
  zira:
    external:
      name: zira
